//English id=1
var TT_language_en = new Array();
TT_language_en["cambialotodo.message.shoppingCartIsEmpty"]        = 'Shopping cart is empty!';
TT_language_en["cambialotodo.common.continueShopping"]            = 'Continue Shopping';
TT_language_en["cambialotodo.message.cannotBeEmpty"]              = 'Can\'t be empty!';
TT_language_en["cambialotodo.common.tip"]                         = 'Tip';
TT_language_en["cambialotodo.message.enterYourEmail"]             = 'Please enter your email address.';
TT_language_en["cambialotodo.message.wrongEmail"]                 = 'You\'ve entered the wrong email format!';
TT_language_en["cambialotodo.product.ok"]                         = 'Ok';//ok
TT_language_en["cambialotodo.product.cancel"]                     = 'Cancel';//ok
TT_language_en["cambialotodo.product.name"]                       = 'Name';//ok
TT_language_en["cambialotodo.product.mobilePhone"]                = 'Mobile Phone';//ok
TT_language_en["cambialotodo.product.emailAddress"]               = 'E-mail address';//ok
TT_language_en["cambialotodo.product.yourTargetPrice"]            = 'Your Target Price';//ok
TT_language_en["cambialotodo.product.orderQuantity"]              = 'Order Quantity';//ok
TT_language_en["cambialotodo.product.countryState"]               = 'Country &#47; State';//ok
TT_language_en["cambialotodo.product.companyName"]                = 'Company Name';//ok
TT_language_en["cambialotodo.product.writeAnInquiry"]             = 'Write an inquiry';//ok
TT_language_en["cambialotodo.product.pleaseLetUsKnow"]            = 'Please let us know as much as possible about your inquiry so that we can assist you with your specific needs. We are always happy to help wherever possible.';                        //ok
TT_language_en["cambialotodo.product.item"]                       = 'Item';//ok
TT_language_en["cambialotodo.common.itemAddedToCart"]            = 'item added to cart';
TT_language_en["cambialotodo.common.totalItemInYourCart"]        = 'total item in your cart';
TT_language_en["cambialotodo.common.viewCart"]                   = 'View Cart';
TT_language_en["cambialotodo.product.addToCart"]                  = 'Add To Cart';//ok
TT_language_en["cambialotodo.common.viewMore"]                   = 'View More';
TT_language_en["cambialotodo.message.enterYourPassword"]    = 'Please enter your password.';
TT_language_en["cambialotodo.message.usernameOrPassword"]         = 'You\'ve entered an incorrect username or password.';
TT_language_en["cambialotodo.common.signIn"]                     = 'Sign In';
TT_language_en["cambialotodo.common.signInWithcambialotodoAccount"]    = 'Sign in with cambialotodo account';//ok
TT_language_en["cambialotodo.common.enterYourEmail"]             = 'Enter your email';//ok
TT_language_en["cambialotodo.common.enterYourPassword"]          = 'Enter your password';//ok
TT_language_en["cambialotodo.common.forgotPassword"]             = 'Forgot password';//ok
TT_language_en["cambialotodo.common.signInWithAnExistingAccount"]= 'Sign In with An Existing Account';//ok
TT_language_en["cambialotodo.common.joinToday"]                  = 'Join today';//ok
TT_language_en["cambialotodo.common.membersOnlyService"]         = 'Members Only Service';//ok
TT_language_en["cambialotodo.common.membersOnlyService1"]        = 'Reward Points';//ok
TT_language_en["cambialotodo.common.membersOnlyService2"]        = 'Exclusive Customer Service';//ok
TT_language_en["cambialotodo.common.membersOnlyService3"]        = 'Personalized Recommendations';//ok
TT_language_en["cambialotodo.common.membersOnlyService4"]        = 'Parmanent Shopping Cart';//ok
TT_language_en["cambialotodo.common.membersOnlyService5"]        = 'Order History';//ok
TT_language_en["cambialotodo.common.error"]                      = 'Error';
TT_language_en["cambialotodo.common.successfully"]               = 'Successfully';
TT_language_en["cambialotodo.common.viewCartCheckOut"]           = 'View Cart & Check out';//ok
TT_language_en["cambialotodo.common.inStock"]                    = 'In Stock';
TT_language_en["cambialotodo.common.outStock"]                   = 'Out of Stock';
TT_language_en["cambialotodo.product.regularPrice"]              = 'Regular Price';
TT_language_en["cambialotodo.product.saleEndsIn"]                = 'Sale Ends in';

TT_language_en["cambialotodo.common.chinaWarehouse"]             = 'China Warehouse';
TT_language_en["cambialotodo.common.ukWarehouse"]                = 'UK Warehouse';
TT_language_en["cambialotodo.common.italyWarehouse"]             = 'Italy Warehouse';
TT_language_en["cambialotodo.common.germanyWarehouse"]           = 'Germany Warehouse';
TT_language_en["cambialotodo.common.usWarehouse"]                = 'US Warehouse';
TT_language_en["cambialotodo.common.franceWarehouse"]            = 'France Warehouse';
TT_language_en["cambialotodo.common.spainWarehouse"]             = 'Spain Warehouse';
TT_language_en["cambialotodo.common.australiaWarehouse"]         = 'Australia Warehouse';
TT_language_en["cambialotodo.product.shippingFrom"]              = 'Ship From';
TT_language_en["cambialotodo.product.warehouse"]                 = 'Warehouse';
TT_language_en["cambialotodo.shippingmethod.freeshipping"]       = 'FREE SHIPPING';
TT_language_en["cambialotodo.shippingmethod.noshipping"]         = 'This item can\'t be shipped';
TT_language_en["cambialotodo.shippingmethod.to"]                 = 'to';
TT_language_en["cambialotodo.shippingmethod.via"]                = 'via';
TT_language_en["cambialotodo.lottery.continueToDraw"]             = 'Continue to draw';
TT_language_en["cambialotodo.lottery.againDrawing"]               = 'Again drawing';
TT_language_en["cambialotodo.lottery.continueLater"]              = 'Continue later';
TT_language_en["cambialotodo.lottery.cancelTheDraw"]              = 'Cancel the draw';
TT_language_en["cambialotodo.product.pcsSold"]                   = 'pcs sold';
TT_language_en["cambialotodo.common.viewLess"]                   = 'View Less';
TT_language_en["cambialotodo.common.preorder"]                   = 'Preorder';
TT_language_en["cambialotodo.common.yes"]                        = 'Yes';
TT_language_en["cambialotodo.common.no"]                         = 'No';
TT_language_en["cambialotodo.common.youMayalsolike"]             = 'Products You Might Like';
//Português id=8
var TT_language_pt = new Array();
TT_language_pt["cambialotodo.message.shoppingCartIsEmpty"]       = 'O carrinho de compra está vazio!';
TT_language_pt["cambialotodo.common.continueShopping"]           = 'Continue comprado';
TT_language_pt["cambialotodo.message.cannotBeEmpty"]              = 'Não Pode ser vazio!';
TT_language_pt["cambialotodo.common.tip"]                        = 'Ponta';
TT_language_pt["cambialotodo.message.enterYourEmail"]            = 'Por favor, entra o seu endereço de e-mail.';
TT_language_pt["cambialotodo.message.wrongEmail"]                = 'Você entra a erra forma de endreço de e-mail';
TT_language_pt["cambialotodo.product.ok"]                        = 'Ok';//ok
TT_language_pt["cambialotodo.product.cancel"]                    = 'Cancelar';//ok
TT_language_pt["cambialotodo.product.name"]                      = 'Nome';//ok
TT_language_pt["cambialotodo.product.mobilePhone"]               = 'Celular';//ok
TT_language_pt["cambialotodo.product.emailAddress"]              = 'Endereço de e-mail';//ok
TT_language_pt["cambialotodo.product.yourTargetPrice"]           = 'Seu Destino de Preço';//ok
TT_language_pt["cambialotodo.product.orderQuantity"]             = 'Quantidade de ordem';//ok
TT_language_pt["cambialotodo.product.countryState"]              = 'País / Estado';//ok
TT_language_pt["cambialotodo.product.companyName"]               = 'Nome da Empresa';//ok
TT_language_pt["cambialotodo.product.writeAnInquiry"]            = 'Escreva um inquérito';//ok
TT_language_pt["cambialotodo.product.pleaseLetUsKnow"]           = 'Por favor, deixe-nos saber o máximo possível sobre sua pergunta para que possamos ajudá-lo com suas necessidades específicas. Estamos sempre dispostos a ajudar sempre que possível.';//ok
TT_language_pt["cambialotodo.product.item"]                      = 'Item';//ok
TT_language_pt["cambialotodo.common.itemAddedToCart"]           = 'Adiciona o item no carrinho de compra';
TT_language_pt["cambialotodo.common.totalItemInYourCart"]        = 'Todos itens no seu carrinho';
TT_language_pt["cambialotodo.common.viewCart"]                   = 'Ver Carrinho';
TT_language_pt["cambialotodo.product.addToCart"]                 = 'Adicionar ao Carinho';//ok
TT_language_pt["cambialotodo.common.viewMore"]                   = 'Veja mais';
TT_language_pt["cambialotodo.message.enterYourPassword"]         = 'Por favor, entra a sua senha.';
TT_language_pt["cambialotodo.message.usernameOrPassword"]         = 'Você entra a senha ou o nome de usário que é erro';
TT_language_pt["cambialotodo.common.signIn"]                     = 'Assinar em';	//ok
TT_language_pt["cambialotodo.common.signInWithcambialotodoAccount"]    = 'Entrar com Conta cambialotodo';//ok
TT_language_pt["cambialotodo.common.enterYourEmail"]             = 'Digite seu e-mail';//ok
TT_language_pt["cambialotodo.common.enterYourPassword"]          = 'Coloque sua senha';//ok
TT_language_pt["cambialotodo.common.forgotPassword"]             = 'Se esquece a senha?';//ok
TT_language_pt["cambialotodo.common.signInWithAnExistingAccount"]= 'Entrar com uma Conta Existente';//ok
TT_language_pt["cambialotodo.common.joinToday"]                  = 'Gozar hoje!';//ok
TT_language_pt["cambialotodo.common.membersOnlyService"]         = 'Serviço para Membros';//ok
TT_language_pt["cambialotodo.common.membersOnlyService1"]        = '1.Reward Pontos';//ok
TT_language_pt["cambialotodo.common.membersOnlyService2"]        = '2.Exclusive Atendimento ao Cliente';//ok
TT_language_pt["cambialotodo.common.membersOnlyService3"]        = '3.Recomendações Personalized';//ok
TT_language_pt["cambialotodo.common.membersOnlyService4"]        = '4.Permanent Carrinho';//ok
TT_language_pt["cambialotodo.common.membersOnlyService5"]        = '5.Order História';//ok
TT_language_pt["cambialotodo.common.error"]                      = 'Erro';
TT_language_pt["cambialotodo.common.successfully"]               = 'Sucesso';
TT_language_pt["cambialotodo.common.viewCartCheckOut"]           = 'Ver Carrinho';//ok
TT_language_pt["cambialotodo.common.inStock"]                    = 'Em estoque';
TT_language_pt["cambialotodo.common.outStock"]                   = 'Sem Stoque';
TT_language_pt["cambialotodo.product.regularPrice"]              = 'Preço Normal';
TT_language_pt["cambialotodo.product.saleEndsIn"]                = 'Venda Termina em';

TT_language_pt["cambialotodo.common.chinaWarehouse"]             = 'Armazém de China';
TT_language_pt["cambialotodo.common.ukWarehouse"]                = 'Armazém do Reino Unido';
TT_language_pt["cambialotodo.common.italyWarehouse"]             = 'Armazém de Itália';
TT_language_pt["cambialotodo.common.germanyWarehouse"]           = 'Armazém de Alemanha';
TT_language_pt["cambialotodo.common.usWarehouse"]                = 'Armazém de Estados Unidos';
TT_language_pt["cambialotodo.common.franceWarehouse"]            = 'Armazém de França';
TT_language_pt["cambialotodo.common.spainWarehouse"]             = 'Armazém de Espanha';
TT_language_pt["cambialotodo.common.australiaWarehouse"]         = 'Armazém de Austrália';
TT_language_pt["cambialotodo.product.shippingFrom"]              = 'Envio de';
TT_language_pt["cambialotodo.product.warehouse"]                 = 'Armazém';
TT_language_pt["cambialotodo.shippingmethod.freeshipping"]       = 'Frete Grátis';
TT_language_pt["cambialotodo.shippingmethod.noshipping"]         = 'Este item não pode ser enviado';
TT_language_pt["cambialotodo.shippingmethod.to"]                 = 'a';
TT_language_pt["cambialotodo.shippingmethod.via"]                = 'via';
TT_language_pt["cambialotodo.lottery.continueToDraw"]             = 'Continuar a desenhar';
TT_language_pt["cambialotodo.lottery.againDrawing"]               = 'Novamente desenho';
TT_language_pt["cambialotodo.lottery.continueLater"]              = 'Continuar mais tarde';
TT_language_pt["cambialotodo.lottery.cancelTheDraw"]              = 'Cancelar o sorteio';
TT_language_pt["cambialotodo.product.pcsSold"]                     = 'vendidos';
TT_language_pt["cambialotodo.common.viewLess"]                   = 'Ver menos';
TT_language_pt["cambialotodo.common.preorder"]                   = 'Pre-order';
TT_language_pt["cambialotodo.common.yes"]                        = 'Sim';
TT_language_pt["cambialotodo.common.no"]                         = 'Não';
TT_language_pt["cambialotodo.common.youMayalsolike"]             = 'Talvez Gosta deste Porductos';
//Español  id=2
var TT_language_es = new Array();
TT_language_es["cambialotodo.message.shoppingCartIsEmpty"]        = 'El carrito de compras es vacío.';//ok
TT_language_es["cambialotodo.common.continueShopping"]            = 'Siga comprando.';//ok
TT_language_es["cambialotodo.message.cannotBeEmpty"]              = 'No se puede estar vacío!';//ok
TT_language_es["cambialotodo.common.tip"]                         = 'Consejo';//ok
TT_language_es["cambialotodo.message.enterYourEmail"]             = 'Por favor ingrese tu dirección de correo electrónico.';//ok
TT_language_es["cambialotodo.message.wrongEmail"]                 = 'Has entrado en el formato de correo electrónico mal!';//ok
TT_language_es["cambialotodo.product.ok"]                         = 'Ok';//ok
TT_language_es["cambialotodo.product.cancel"]                     = 'cancelar';//ok
TT_language_es["cambialotodo.product.name"]                       = 'nombre';//ok
TT_language_es["cambialotodo.product.mobilePhone"]                = 'móvil';//ok
TT_language_es["cambialotodo.product.emailAddress"]               = 'Dirección de correo electrónico';//ok
TT_language_es["cambialotodo.product.yourTargetPrice"]            = 'Tu precio deseado';//ok
TT_language_es["cambialotodo.product.orderQuantity"]              = 'cantidad del orden';//ok
TT_language_es["cambialotodo.product.countryState"]               = 'País &#47 Estado';//ok
TT_language_es["cambialotodo.product.companyName"]                = 'Nombre de compañía';//ok
TT_language_es["cambialotodo.product.writeAnInquiry"]             = 'Escribe una investigación';//ok
TT_language_es["cambialotodo.product.pleaseLetUsKnow"]            = 'Por favor, háganos saber lo más posible acerca de su pregunta para que nosotros le podemos ayudar con sus necesidades específicas. Siempre estamos dispuestos a ayudar que sea posible.';                        //ok
TT_language_es["cambialotodo.product.item"]                       = 'artículo';//ok
TT_language_es["cambialotodo.common.itemAddedToCart"]             = 'artículo ha añadido a la carrito';
TT_language_es["cambialotodo.common.totalItemInYourCart"]         = 'total artículo en su carrito';
TT_language_es["cambialotodo.common.viewCart"]                    = 'Ver el carrito';
TT_language_es["cambialotodo.product.addToCart"]                  = 'Añadir al carrito';//ok
TT_language_es["cambialotodo.common.viewMore"]                    = 'Ver más';
TT_language_es["cambialotodo.message.enterYourPassword"]          = 'Por favor ingrese tu contraseña';
TT_language_es["cambialotodo.message.usernameOrPassword"]         = 'Usted ha pasado un nombre de usuario incorrecto o contraseña incorrecta.';
TT_language_es["cambialotodo.common.signIn"]                     = 'Ingresar';
TT_language_es["cambialotodo.common.signInWithcambialotodoAccount"]    = 'Ingresa con la cuenta de cambialotodo';//ok
TT_language_es["cambialotodo.common.enterYourEmail"]             = 'Entra tu email';//ok
TT_language_es["cambialotodo.common.enterYourPassword"]          = 'Entra tu contraseña';//ok
TT_language_es["cambialotodo.common.forgotPassword"]             = '¿Has olvidado tu contraseña?';//ok
TT_language_es["cambialotodo.common.signInWithAnExistingAccount"]= 'Ingresa con una cuenta existida';//ok
TT_language_es["cambialotodo.common.joinToday"]                  = '¡Únete hoy!';//ok
TT_language_es["cambialotodo.common.membersOnlyService"]         = 'Privilegios de Miembros';//ok
TT_language_es["cambialotodo.common.membersOnlyService1"]        = '1.Puntos de Recompensa';//ok
TT_language_es["cambialotodo.common.membersOnlyService2"]        = '2.Servicio Exclusivo al Cliente';//ok
TT_language_es["cambialotodo.common.membersOnlyService3"]        = '3.Recomendaciones Personalizadas';//ok
TT_language_es["cambialotodo.common.membersOnlyService4"]        = '4.Carrito Permanente';//ok
TT_language_es["cambialotodo.common.membersOnlyService5"]        = '5.Pedidos de Historia';//ok
TT_language_es["cambialotodo.common.error"]                      = 'Error';
TT_language_es["cambialotodo.common.successfully"]               = 'con éxito';
TT_language_es["cambialotodo.common.viewCartCheckOut"]           = 'Ver el carrito';//ok
TT_language_es["cambialotodo.common.inStock"]                    = 'Disponible';
TT_language_es["cambialotodo.common.outStock"]                   = 'Fuera de stock';
TT_language_es["cambialotodo.product.regularPrice"]              = 'Precio regular';
TT_language_es["cambialotodo.product.saleEndsIn"]                = 'Termina la venta';

TT_language_es["cambialotodo.common.chinaWarehouse"]             = 'Almacén de China';
TT_language_es["cambialotodo.common.ukWarehouse"]                = 'Almacén de Reino Unido';
TT_language_es["cambialotodo.common.italyWarehouse"]             = 'Almacén de Italia';
TT_language_es["cambialotodo.common.germanyWarehouse"]           = 'Almacén de Alemania';
TT_language_es["cambialotodo.common.usWarehouse"]                = 'Almacén de Estados Unidos';
TT_language_es["cambialotodo.common.franceWarehouse"]            = 'Almacén de Francia';
TT_language_es["cambialotodo.common.spainWarehouse"]             = 'Almacén de España';
TT_language_es["cambialotodo.common.australiaWarehouse"]         = 'Almacén de Australia';
TT_language_es["cambialotodo.product.shippingFrom"]              = 'Enviar desde';
TT_language_es["cambialotodo.product.warehouse"]                 = 'almacén ';
TT_language_es["cambialotodo.shipping.canNotShipTo"]             = 'no se puede enviar a';
TT_language_es["cambialotodo.shippingmethod.freeshipping"]       = 'Envío Gratis';
TT_language_es["cambialotodo.shippingmethod.noshipping"]         = 'Este artículo no puede enviarse';
TT_language_es["cambialotodo.shippingmethod.to"]                 = 'a';
TT_language_es["cambialotodo.shippingmethod.via"]                = 'vía';
TT_language_es["cambialotodo.lottery.continueToDraw"]             = 'Seguir dibujando';
TT_language_es["cambialotodo.lottery.againDrawing"]               = 'De nuevo dibujo';
TT_language_es["cambialotodo.lottery.continueLater"]              = 'Continuar más tarde';
TT_language_es["cambialotodo.lottery.cancelTheDraw"]              = 'Cancelar el sorteo';
TT_language_es["cambialotodo.product.pcsSold"]                     = 'vendidas';
TT_language_es["cambialotodo.common.viewLess"]                   = 'Ver menos';
TT_language_es["cambialotodo.common.preorder"]                   = 'Pre-order';
TT_language_es["cambialotodo.common.yes"]                        = 'Sí';
TT_language_es["cambialotodo.common.no"]                         = 'No';
TT_language_es["cambialotodo.common.youMayalsolike"]             = 'Productos que podrían gustarte.';
//???????  id=3
var TT_language_ru = new Array();
TT_language_ru["cambialotodo.message.shoppingCartIsEmpty"]                  = '???? ??????? ?????';
TT_language_ru["cambialotodo.common.continueShopping"]           = '?????????? ???????';
TT_language_ru["cambialotodo.message.cannotBeEmpty"]              = '?? ????? ???? ??????!';
TT_language_ru["cambialotodo.common.tip"]                        = '???';
TT_language_ru["cambialotodo.message.enterYourEmail"]          = '??????? ????? ??????????? ?????';
TT_language_ru["cambialotodo.message.wrongEmail"]           = '?? ????? ???????? ?????? ??????????? ?????!';
TT_language_ru["cambialotodo.product.ok"]                         = 'Ok';//ok
TT_language_ru["cambialotodo.product.cancel"]                     = '??????';//ok
TT_language_ru["cambialotodo.product.name"]                       = '???';//ok
TT_language_ru["cambialotodo.product.mobilePhone"]                = '????????? ???????';//ok
TT_language_ru["cambialotodo.product.emailAddress"]               = '????? ??????????? ?????';//ok
TT_language_ru["cambialotodo.product.yourTargetPrice"]            = '???? ??????? ????';//ok
TT_language_ru["cambialotodo.product.orderQuantity"]              = '?????????? ??????????';//ok
TT_language_ru["cambialotodo.product.countryState"]               = '????';//ok
TT_language_ru["cambialotodo.product.companyName"]                = '???????? ????????';//ok
TT_language_ru["cambialotodo.product.writeAnInquiry"]             = '???????? ??????';//ok
TT_language_ru["cambialotodo.product.pleaseLetUsKnow"]            = '??????????, ???????? ??? ????? ?????? ?????????? ? ????? ???????, ??? ??? ?? ?? ????? ?????? ??? ? ?????? ??????????? ?????????????. ?? ?????? ???? ??????, ??? ?????.';                        //ok
TT_language_ru["cambialotodo.product.item"]                       = '?????';//ok
TT_language_ru["cambialotodo.common.itemAddedToCart"]            = '????? ???????? ? ???????';
TT_language_ru["cambialotodo.common.totalItemInYourCart"]        = '??? ?????? ? ????? ???????';
TT_language_ru["cambialotodo.common.viewCart"]                   = '???????';
TT_language_ru["cambialotodo.product.addToCart"]                  = '???????? ? ???????';//ok
TT_language_ru["cambialotodo.common.viewMore"]                   = '??????????? ??????';
TT_language_ru["cambialotodo.message.enterYourPassword"]    = '?????????? ??????? ??? ??????.';
TT_language_ru["cambialotodo.message.usernameOrPassword"]         = '?? ????? ???????????? ????? ??? ??????.';
TT_language_ru["cambialotodo.common.signIn"]                     = '????? ? ???????';
TT_language_ru["cambialotodo.common.signInWithcambialotodoAccount"]    = '????? ? ??????? cambialotodo';//ok
TT_language_ru["cambialotodo.common.enterYourEmail"]             = '??????? ????? ??????????? ?????';//ok
TT_language_ru["cambialotodo.common.enterYourPassword"]          = '??????? ??? ??????';//ok
TT_language_ru["cambialotodo.common.forgotPassword"]             = '?????? ???????';//ok
TT_language_ru["cambialotodo.common.signInWithAnExistingAccount"]= '???? ? ???????????? ???????';//ok
TT_language_ru["cambialotodo.common.joinToday"]                  = '????????????? ???????!';//ok
TT_language_ru["cambialotodo.common.membersOnlyService"]         = '?????? ?????? ??? ?????????????';//ok
TT_language_ru["cambialotodo.common.membersOnlyService1"]        = '1.?????????? ????';//ok
TT_language_ru["cambialotodo.common.membersOnlyService2"]        = '2.???????????? ???????????? ????????';//ok
TT_language_ru["cambialotodo.common.membersOnlyService3"]        = '3.?????? ????????????';//ok
TT_language_ru["cambialotodo.common.membersOnlyService4"]        = '4.?????????? ???????';//ok
TT_language_ru["cambialotodo.common.membersOnlyService5"]        = '5.??????? ???????';//ok
TT_language_ru["cambialotodo.common.error"]                      = '??????';
TT_language_ru["cambialotodo.common.successfully"]               = '???????';
TT_language_ru["cambialotodo.common.viewCartCheckOut"]           = '???????';//ok
TT_language_ru["cambialotodo.common.inStock"]                    = '? ???????';
TT_language_ru["cambialotodo.common.outStock"]                   = '??? ?? ??????';
TT_language_ru["cambialotodo.product.regularPrice"]              = '??????? ????';
TT_language_ru["cambialotodo.product.saleEndsIn"]                = '????????? ?????? ?';

TT_language_ru["cambialotodo.common.chinaWarehouse"]             = '????? ?????';
TT_language_ru["cambialotodo.common.ukWarehouse"]                = '??????????? ??????????? ?????';
TT_language_ru["cambialotodo.common.italyWarehouse"]             = '????? ? ??????';
TT_language_ru["cambialotodo.common.germanyWarehouse"]           = '????? ? ????????';
TT_language_ru["cambialotodo.common.usWarehouse"]                = '????? ???';
TT_language_ru["cambialotodo.common.franceWarehouse"]            = '??????? ?????';
TT_language_ru["cambialotodo.common.spainWarehouse"]             = '??????? ?????';
TT_language_ru["cambialotodo.common.australiaWarehouse"]         = '????????? ?????';
TT_language_ru["cambialotodo.product.shippingFrom"]              = '???????? ??';
TT_language_ru["cambialotodo.product.warehouse"]                 = '????? ';
TT_language_ru["cambialotodo.shippingmethod.freeshipping"]       = '?????????? ????????';
TT_language_ru["cambialotodo.shippingmethod.noshipping"]         = '???? ????? ?? ????? ???? ?????????';
TT_language_ru["cambialotodo.shippingmethod.to"]                 = '??';
TT_language_ru["cambialotodo.shippingmethod.via"]                = '?????';
TT_language_ru["cambialotodo.lottery.continueToDraw"]             = '??????????? ????????';
TT_language_ru["cambialotodo.lottery.againDrawing"]               = '????? ?? ???????';
TT_language_ru["cambialotodo.lottery.continueLater"]              = '?????????? ?????';
TT_language_ru["cambialotodo.lottery.cancelTheDraw"]              = '???????? ?????';
TT_language_ru["cambialotodo.product.pcsSold"]                     = '???????';
TT_language_ru["cambialotodo.common.viewLess"]                   = '???????? ??????';
TT_language_ru["cambialotodo.common.preorder"]                   = '?????????';
TT_language_ru["cambialotodo.common.yes"]                        = '??';
TT_language_ru["cambialotodo.common.no"]                         = '???';
TT_language_ru["cambialotodo.common.youMayalsolike"]             = 'Productos que podrían gustarte.';
//Deutsch  id=4
var TT_language_de = new Array();
TT_language_de["cambialotodo.message.shoppingCartIsEmpty"]        = 'Der Warenkorb ist leer!';
TT_language_de["cambialotodo.common.continueShopping"]            = 'Mit dem Einkaufen fortfahren';
TT_language_de["cambialotodo.message.cannotBeEmpty"]              = 'Darf nicht leer sein!';
TT_language_de["cambialotodo.common.tip"]                         = 'Spitze';
TT_language_de["cambialotodo.message.enterYourEmail"]             = 'Geben Sie bitte Ihre Email-Adresse ein.';
TT_language_de["cambialotodo.message.wrongEmail"]                 = 'Sie haben die falsche E-Mail-Format eingegeben!';
TT_language_de["cambialotodo.product.ok"]                         = 'Ok';//ok
TT_language_de["cambialotodo.product.cancel"]                     = 'Absagen';//ok
TT_language_de["cambialotodo.product.name"]                       = 'Name';//ok
TT_language_de["cambialotodo.product.mobilePhone"]                = 'Handy';//ok
TT_language_de["cambialotodo.product.emailAddress"]               = 'E-Mail-Addresse';//ok
TT_language_de["cambialotodo.product.yourTargetPrice"]            = 'Ihr Zielpreis';//ok
TT_language_de["cambialotodo.product.orderQuantity"]              = 'Bestellmenge';//ok
TT_language_de["cambialotodo.product.countryState"]               = 'Land &#47; Region';//ok
TT_language_de["cambialotodo.product.companyName"]                = 'Name der Firma';//ok
TT_language_de["cambialotodo.product.writeAnInquiry"]             = 'Schreiben Sie eine Anfrage';//ok
TT_language_de["cambialotodo.product.pleaseLetUsKnow"]            = 'Bitte lassen Sie uns Ihre Anfrage baldmöglichst wissen , damit wir Ihnen mit Ihren spezifischen Bedürfnissen zu unterstützen. Wir sind immer glücklich zu helfen, wo immer möglich.';                        //ok
TT_language_de["cambialotodo.product.item"]                       = 'Artikel';//ok
TT_language_de["cambialotodo.common.itemAddedToCart"]            = 'Artikel wurde dem Warenkorb hinzugefügt';
TT_language_de["cambialotodo.common.totalItemInYourCart"]        = 'Gesamt Artikel in den Warenkorb';
TT_language_de["cambialotodo.common.viewCart"]                   = 'Zum Warenkorb';
TT_language_de["cambialotodo.product.addToCart"]                  = 'In den Warenkorb legen';//ok
TT_language_de["cambialotodo.common.viewMore"]                   = 'Mehr anzeigen';
TT_language_de["cambialotodo.message.enterYourPassword"]         = 'Bitte geben Sie Ihr Passwort ein.';
TT_language_de["cambialotodo.message.usernameOrPassword"]         = 'Sie haben einen falschen Benutzername oder Passwort eingegeben.';
TT_language_de["cambialotodo.common.signIn"]                     = '"Anmelden';
TT_language_de["cambialotodo.common.signInWithcambialotodoAccount"]    = 'Anmeldung mit cambialotodo Konto';//ok
TT_language_de["cambialotodo.common.enterYourEmail"]             = 'Geben Sie Ihre Email-Adresse ein';//ok
TT_language_de["cambialotodo.common.enterYourPassword"]          = 'Geben Sie Ihr Passwort';//ok
TT_language_de["cambialotodo.common.forgotPassword"]             = 'Passwort vergessen?';//ok
TT_language_de["cambialotodo.common.signInWithAnExistingAccount"]= 'Einloggen mit einem bestehenden Konto';//ok
TT_language_de["cambialotodo.common.joinToday"]                  = 'Tritt heute bei!';//ok
TT_language_de["cambialotodo.common.membersOnlyService"]         = 'Nur für Mitglieder des Service';//ok
TT_language_de["cambialotodo.common.membersOnlyService1"]        = '1.Reward Punkte';//ok
TT_language_de["cambialotodo.common.membersOnlyService2"]        = '2.Exclusive Kundenservice';//ok
TT_language_de["cambialotodo.common.membersOnlyService3"]        = '3.Personalized Empfehlungen';//ok
TT_language_de["cambialotodo.common.membersOnlyService4"]        = '4.kprmanent Einkaufswagen';//ok
TT_language_de["cambialotodo.common.membersOnlyService5"]        = '5.Order Geschichte';//ok
TT_language_de["cambialotodo.common.error"]                      = 'Fehler';
TT_language_de["cambialotodo.common.successfully"]               = 'Erfolgreich';
TT_language_de["cambialotodo.common.viewCartCheckOut"]           = 'Zum Warenkorb';//ok
TT_language_de["cambialotodo.common.inStock"]                    = 'Auf Lager';
TT_language_de["cambialotodo.common.outStock"]                   = 'Ausverkauft';
TT_language_de["cambialotodo.product.regularPrice"]              = 'Normalpreis';
TT_language_de["cambialotodo.product.saleEndsIn"]                = 'Verkauf endet in';

TT_language_de["cambialotodo.common.chinaWarehouse"]             = 'China-Lager';
TT_language_de["cambialotodo.common.ukWarehouse"]                = 'Großbritannien-Lager';
TT_language_de["cambialotodo.common.italyWarehouse"]             = 'Italien-Lager';
TT_language_de["cambialotodo.common.germanyWarehouse"]           = 'Deutschland-Lager';
TT_language_de["cambialotodo.common.usWarehouse"]                = 'USA-Lager';
TT_language_de["cambialotodo.common.franceWarehouse"]            = 'Frankreich-Lager';
TT_language_de["cambialotodo.common.spainWarehouse"]             = 'Spanien-Lager';
TT_language_de["cambialotodo.common.australiaWarehouse"]         = 'Australien-Lager';
TT_language_de["cambialotodo.product.shippingFrom"]              = 'Versand von';
TT_language_de["cambialotodo.product.warehouse"]                 = 'Lager ';
TT_language_de["cambialotodo.shippingmethod.freeshipping"]       = 'Kostenloser Versand';
TT_language_de["cambialotodo.shippingmethod.noshipping"]         = 'Dieser Artikel kann nicht versendet werden';
TT_language_de["cambialotodo.shippingmethod.to"]                 = 'nach';
TT_language_de["cambialotodo.shippingmethod.via"]                = 'über';
TT_language_de["cambialotodo.lottery.continueToDraw"]             = 'Weiter zu zeichnen';
TT_language_de["cambialotodo.lottery.againDrawing"]               = 'Wieder Zeichnung';
TT_language_de["cambialotodo.lottery.continueLater"]              = 'Fahren Sie fort';
TT_language_de["cambialotodo.lottery.cancelTheDraw"]              = 'Brechen Sie das Unentschieden ab';
TT_language_de["cambialotodo.product.pcsSold"]                     = 'verkauft';
TT_language_de["cambialotodo.common.viewLess"]                   = 'Weniger anzeigen';
TT_language_de["cambialotodo.common.preorder"]                   = 'Vorbestellung';
TT_language_de["cambialotodo.common.yes"]                        = 'Ja';
TT_language_de["cambialotodo.common.no"]                         = 'Nein';
TT_language_de["cambialotodo.common.youMayalsolike"]             = 'Produkte, die du vielleicht magst';
//Français id=5
var TT_language_fr = new Array();
TT_language_fr["cambialotodo.message.shoppingCartIsEmpty"]        = 'Le panier d\'achat est vide!';
TT_language_fr["cambialotodo.common.continueShopping"]            = 'Continuer mes achats';
TT_language_fr["cambialotodo.message.cannotBeEmpty"]              = 'Vous ne pouvez pas être vide!';
TT_language_fr["cambialotodo.common.tip"]                         = 'Pointe';
TT_language_fr["cambialotodo.message.enterYourEmail"]             = 'Entrez votre adresse e-mail,s\'il vous plaît!';
TT_language_fr["cambialotodo.message.wrongEmail"]                 = 'Vous avez entré le format e-mail erronée!';
TT_language_fr["cambialotodo.product.ok"]                         = 'D\'accord';//ok
TT_language_fr["cambialotodo.product.cancel"]                     = 'Annuler';//ok
TT_language_fr["cambialotodo.product.name"]                       = 'prénom';//ok
TT_language_fr["cambialotodo.product.mobilePhone"]                = 'Portable';//ok
TT_language_fr["cambialotodo.product.emailAddress"]               = 'Adresse d\'e-mail';//ok
TT_language_fr["cambialotodo.product.yourTargetPrice"]            = 'Votre prix cible';//ok
TT_language_fr["cambialotodo.product.orderQuantity"]              = 'Quantité de Commande';//ok
TT_language_fr["cambialotodo.product.countryState"]               = 'Etat';//ok
TT_language_fr["cambialotodo.product.companyName"]                = 'Nom de la compagnie';//ok
TT_language_fr["cambialotodo.product.writeAnInquiry"]             = 'Écrivez une enquête';//ok
TT_language_fr["cambialotodo.product.pleaseLetUsKnow"]            = 'laissez-nous savoir autant que possible sur votre demande afin que nous puissions vous aider avec vos besoins spécifiques,S\'il vous plaît . Nous sommes toujours heureux d\'aider autant que possible.';                        //ok
TT_language_fr["cambialotodo.product.item"]                       = 'Article';//ok
TT_language_fr["cambialotodo.common.itemAddedToCart"]            = 'article ajouté au panier';
TT_language_fr["cambialotodo.common.totalItemInYourCart"]        = 'article totale dans votre panier';
TT_language_fr["cambialotodo.common.viewCart"]                   = 'Voir le panier';
TT_language_fr["cambialotodo.product.addToCart"]                  = 'Ajouter au panier';//ok
TT_language_fr["cambialotodo.common.viewMore"]                   = 'Voir plus';
TT_language_fr["cambialotodo.message.enterYourPassword"]        = 'Tapez votre mot de passe';
TT_language_fr["cambialotodo.message.usernameOrPassword"]         = 'Vous avez entré un incorrect nom d\'utilisateur ou incorrecte mot de passe.';
TT_language_fr["cambialotodo.common.signIn"]                     = 'Se connecter';
TT_language_fr["cambialotodo.common.signInWithcambialotodoAccount"]    = 'Connectez-vous avec compte cambialotodo';//ok
TT_language_fr["cambialotodo.common.enterYourEmail"]             = 'Entrer votre Email';//ok
TT_language_fr["cambialotodo.common.enterYourPassword"]          = 'Tapez votre mot de passe';//ok
TT_language_fr["cambialotodo.common.forgotPassword"]             = 'mot de passe oublié?';//ok
TT_language_fr["cambialotodo.common.signInWithAnExistingAccount"]= 'Connectez-vous avec un compte existant';//ok
TT_language_fr["cambialotodo.common.joinToday"]                  = 'Joignez aujourd\'hui!';//ok
TT_language_fr["cambialotodo.common.membersOnlyService"]         = 'Seuls les membres de services';//ok
TT_language_fr["cambialotodo.common.membersOnlyService1"]        = '1.Points de récompense';//ok
TT_language_fr["cambialotodo.common.membersOnlyService2"]        = '2.Service à la clientèle exclusif';//ok
TT_language_fr["cambialotodo.common.membersOnlyService3"]        = '3.recommandations personnalisées';//ok
TT_language_fr["cambialotodo.common.membersOnlyService4"]        = '4.Permanent Panier';//ok
TT_language_fr["cambialotodo.common.membersOnlyService5"]        = '5.Historique des commandes';//ok
TT_language_fr["cambialotodo.common.error"]                      = 'Erreur';
TT_language_fr["cambialotodo.common.successfully"]               = 'Succès';
TT_language_fr["cambialotodo.common.viewCartCheckOut"]           = 'Voir le panier';//ok
TT_language_fr["cambialotodo.common.inStock"]                    = 'En stock';
TT_language_fr["cambialotodo.common.outStock"]                   = 'Rupture de stock';
TT_language_fr["cambialotodo.product.regularPrice"]              = 'Prix habituel';
TT_language_fr["cambialotodo.product.saleEndsIn"]                = 'Vente se termine dans';

TT_language_fr["cambialotodo.common.chinaWarehouse"]             = 'Entrepôt de Chine';
TT_language_fr["cambialotodo.common.ukWarehouse"]                = 'Entrepôt de Royaume-Uni';
TT_language_fr["cambialotodo.common.italyWarehouse"]             = 'Entrepôt d\'Italie';
TT_language_fr["cambialotodo.common.germanyWarehouse"]           = 'Entrepôt d\'Allemagne';
TT_language_fr["cambialotodo.common.usWarehouse"]                = 'Entrepôt des États-Unis';
TT_language_fr["cambialotodo.common.franceWarehouse"]            = 'Entrepôt de France';
TT_language_fr["cambialotodo.common.spainWarehouse"]             = 'Entrepôt d\'Espagne';
TT_language_fr["cambialotodo.common.australiaWarehouse"]         = 'Entrepôt d\'Australie';
TT_language_fr["cambialotodo.product.shippingFrom"]              = 'De expédition';
TT_language_fr["cambialotodo.product.warehouse"]                 = 'Entrepôt';
TT_language_fr["cambialotodo.shippingmethod.freeshipping"]       = 'LIVRAISON GRATUITE';
TT_language_fr["cambialotodo.shippingmethod.noshipping"]         = 'Cet article ne peut être expédié';
TT_language_fr["cambialotodo.shippingmethod.to"]                 = 'à';
TT_language_fr["cambialotodo.shippingmethod.via"]                = 'via';
TT_language_fr["cambialotodo.lottery.continueToDraw"]             = 'Continuer à dessiner';
TT_language_fr["cambialotodo.lottery.againDrawing"]               = 'Encore un dessin';
TT_language_fr["cambialotodo.lottery.continueLater"]              = 'Continuer plus tard';
TT_language_fr["cambialotodo.lottery.cancelTheDraw"]              = 'Annuler le tirage au sort';
TT_language_fr["cambialotodo.product.pcsSold"]                     = 'vendue';
TT_language_fr["cambialotodo.common.viewLess"]                   = 'Voir moins';
TT_language_fr["cambialotodo.common.preorder"]                   = 'pré-commande';
TT_language_fr["cambialotodo.common.yes"]                        = 'Oui';
TT_language_fr["cambialotodo.common.no"]                         = 'Non';
TT_language_fr["cambialotodo.common.youMayalsolike"]             = 'Produits qui pourraient vous intéresser';
//Italiano id = 6
var TT_language_it = new Array();
TT_language_it["cambialotodo.message.shoppingCartIsEmpty"]       = 'Il carrello è vuoto!';
TT_language_it["cambialotodo.common.continueShopping"]           = 'Continua a fare acquisti';
TT_language_it["cambialotodo.message.cannotBeEmpty"]              = 'Non può essere vuoto!';
TT_language_it["cambialotodo.common.tip"]                        = 'Suggerimento';
TT_language_it["cambialotodo.message.enterYourEmail"]          = 'Inserisci il tuo indirizzo email.';
TT_language_it["cambialotodo.message.wrongEmail"]                = 'Il formato e-mail  non corretto!';
TT_language_it["cambialotodo.product.ok"]                        = 'Ok';//ok
TT_language_it["cambialotodo.product.cancel"]                    = 'Cancella';//ok
TT_language_it["cambialotodo.product.name"]                      = 'Nome';//ok
TT_language_it["cambialotodo.product.mobilePhone"]               = 'Cellulare';//ok
TT_language_it["cambialotodo.product.emailAddress"]              = 'Indirizzo email';//ok
TT_language_it["cambialotodo.product.yourTargetPrice"]           = 'Il tuo Prezzo Obiettivo';//ok
TT_language_it["cambialotodo.product.orderQuantity"]             = 'Quantità d\'Ordine';//ok
TT_language_it["cambialotodo.product.countryState"]              = 'Paese / Stato';//ok
TT_language_it["cambialotodo.product.companyName"]               = 'Nome della ditta';//ok
TT_language_it["cambialotodo.product.writeAnInquiry"]            = 'ScrivI una richiesta';//ok
TT_language_it["cambialotodo.product.pleaseLetUsKnow"]           = 'Fateci sapere il più possibile su vostra richiesta in modo che possiamo aiutarvi con le vostre esigenze specifiche. Siamo sempre felici di aiutare per quanto possibile.';//ok
TT_language_it["cambialotodo.product.item"]                      = 'Articolo';//ok
TT_language_it["cambialotodo.common.itemAddedToCart"]           = 'Prodotto aggiunto al carrello';
TT_language_it["cambialotodo.common.totalItemInYourCart"]        = 'Articolo totale nel carrello';
TT_language_it["cambialotodo.common.viewCart"]                   = 'Vedi il Carrello';
TT_language_it["cambialotodo.product.addToCart"]                 = 'Aggiungi al Carrello';//ok
TT_language_it["cambialotodo.common.viewMore"]                   = 'Visualizza altro';
TT_language_it["cambialotodo.message.enterYourPassword"]    = 'Inserisci la tua password.';
TT_language_it["cambialotodo.message.usernameOrPassword"]         = 'Il nome utente o password non corretta.';
TT_language_it["cambialotodo.common.signIn"]                     = 'Registrati';
TT_language_it["cambialotodo.common.signInWithcambialotodoAccount"]    = 'Accedi con conto cambialotodo';//ok
TT_language_it["cambialotodo.common.enterYourEmail"]             = 'Inserisci il tuo indirizzo email';//ok
TT_language_it["cambialotodo.common.enterYourPassword"]          = 'Inserisci la tua codice d\'ordine';//ok
TT_language_it["cambialotodo.common.forgotPassword"]             = 'Ha dimenticato la codice d\'ordine?';//ok
TT_language_it["cambialotodo.common.signInWithAnExistingAccount"]= 'Accedi con un conto esistente';//ok
TT_language_it["cambialotodo.common.joinToday"]                  = 'Unisciti oggi!';//ok
TT_language_it["cambialotodo.common.membersOnlyService"]         = 'Servizi esclusivi ai membri';//ok
TT_language_it["cambialotodo.common.membersOnlyService1"]        = '1.Punti di Ricompensa';//ok
TT_language_it["cambialotodo.common.membersOnlyService2"]        = '2.Exclusive Servizio Clienti';//ok
TT_language_it["cambialotodo.common.membersOnlyService3"]        = '3.Raccomandazioni personalizzato';//ok
TT_language_it["cambialotodo.common.membersOnlyService4"]        = '4.Carrello Permanente';//ok
TT_language_it["cambialotodo.common.membersOnlyService5"]        = '5.Storia d\'Ordine';//ok
TT_language_it["cambialotodo.common.error"]                      = 'Errore';
TT_language_it["cambialotodo.common.successfully"]               = 'Con successo';
TT_language_it["cambialotodo.common.viewCartCheckOut"]           = 'Vedi il Carrello';//ok
TT_language_it["cambialotodo.common.inStock"]                    = 'Disponibile';
TT_language_it["cambialotodo.common.outStock"]                   = 'Esaurito';
TT_language_it["cambialotodo.product.regularPrice"]              = 'Prezzo regolare';
TT_language_it["cambialotodo.product.saleEndsIn"]                = 'Vendita scaduta';

TT_language_it["cambialotodo.common.chinaWarehouse"]             = 'Magazzino della Cina';
TT_language_it["cambialotodo.common.ukWarehouse"]                = 'Regno Unito magazzino';
TT_language_it["cambialotodo.common.italyWarehouse"]             = 'Magazzino in Italia';
TT_language_it["cambialotodo.common.germanyWarehouse"]           = 'Magazzino di Germania';
TT_language_it["cambialotodo.common.usWarehouse"]                = 'Stati Uniti d\'America magazzino';
TT_language_it["cambialotodo.common.franceWarehouse"]            = 'Magazzino di Francia';
TT_language_it["cambialotodo.common.spainWarehouse"]             = 'Magazzino di Spagna';
TT_language_it["cambialotodo.common.australiaWarehouse"]         = 'Magazzino di Australia';
TT_language_it["cambialotodo.product.shippingFrom"]              = 'Spedizione Da';
TT_language_it["cambialotodo.product.warehouse"]                 = 'Magazzino';
TT_language_it["cambialotodo.shippingmethod.freeshipping"]       = 'SPEDIZIONE GRATUITA';
TT_language_it["cambialotodo.shippingmethod.noshipping"]         = 'Questo articolo non può essere spedito';
TT_language_it["cambialotodo.shippingmethod.to"]                 = 'a';
TT_language_it["cambialotodo.shippingmethod.via"]                = 'via';
TT_language_it["cambialotodo.lottery.continueToDraw"]             = 'Continuare a disegnare';
TT_language_it["cambialotodo.lottery.againDrawing"]               = 'Anche in questo caso il disegno';
TT_language_it["cambialotodo.lottery.continueLater"]              = 'continuare tardi';
TT_language_it["cambialotodo.lottery.cancelTheDraw"]              = 'Annulla il sorteggio';
TT_language_it["cambialotodo.product.pcsSold"]                     = 'venduti';
TT_language_it["cambialotodo.common.viewLess"]                   = 'Visualizza meno risultati';
TT_language_it["cambialotodo.common.preorder"]                   = 'Gli ordini di vendita';
TT_language_it["cambialotodo.common.yes"]                        = 'Sì';
TT_language_it["cambialotodo.common.no"]                         = 'No';
TT_language_it["cambialotodo.common.youMayalsolike"]             = 'Prodotti ti consiglia';

//jpan id=7
var TT_language_jp = new Array();
TT_language_jp["cambialotodo.message.shoppingCartIsEmpty"]       = '????????????????';
TT_language_jp["cambialotodo.common.continueShopping"]           = '??????????';
TT_language_jp["cambialotodo.message.cannotBeEmpty"]              = '???????????';
TT_language_jp["cambialotodo.common.tip"]                        = '??';
TT_language_jp["cambialotodo.message.enterYourEmail"]            = '??????????????????';
TT_language_jp["cambialotodo.message.wrongEmail"]                = '????????????????';
TT_language_jp["cambialotodo.product.ok"]                        = '??';//ok
TT_language_jp["cambialotodo.product.cancel"]                    = '?????';//ok
TT_language_jp["cambialotodo.product.name"]                      = '??';//ok
TT_language_jp["cambialotodo.product.mobilePhone"]               = '???';//ok
TT_language_jp["cambialotodo.product.emailAddress"]              = '?????????';//ok
TT_language_jp["cambialotodo.product.yourTargetPrice"]           = '????????';//ok
TT_language_jp["cambialotodo.product.orderQuantity"]             = '????';//ok
TT_language_jp["cambialotodo.product.countryState"]              = '?/?';//ok
TT_language_jp["cambialotodo.product.companyName"]               = '?????';//ok
TT_language_jp["cambialotodo.product.writeAnInquiry"]            = '???????';//ok
TT_language_jp["cambialotodo.product.pleaseLetUsKnow"]           = '????????????????????????????????????????????';//ok
TT_language_jp["cambialotodo.product.item"]                      = '????';//ok
TT_language_jp["cambialotodo.common.itemAddedToCart"]           = '?????????';
TT_language_jp["cambialotodo.common.totalItemInYourCart"]        = '????????';
TT_language_jp["cambialotodo.common.viewCart"]                   = '???????';
TT_language_jp["cambialotodo.product.addToCart"]                 = '???????';//ok
TT_language_jp["cambialotodo.common.viewMore"]                   = '?????';
TT_language_jp["cambialotodo.message.enterYourPassword"]          = '???????????????????';
TT_language_jp["cambialotodo.message.usernameOrPassword"]         = '???????????????????????';
TT_language_jp["cambialotodo.common.signIn"]                     = '?????';
TT_language_jp["cambialotodo.common.signInWithcambialotodoAccount"]    = 'cambialotodo???????????';//ok
TT_language_jp["cambialotodo.common.enterYourEmail"]             = '??????????????';//ok
TT_language_jp["cambialotodo.common.enterYourPassword"]          = '??????????????';//ok
TT_language_jp["cambialotodo.common.forgotPassword"]             = '?????????';//ok
TT_language_jp["cambialotodo.common.signInWithAnExistingAccount"]= '???????????????????';//ok
TT_language_jp["cambialotodo.common.joinToday"]                  = '??????';//ok
TT_language_jp["cambialotodo.common.membersOnlyService"]         = '???????????????';//ok
TT_language_jp["cambialotodo.common.membersOnlyService1"]        = '???????';//ok
TT_language_jp["cambialotodo.common.membersOnlyService2"]        = '???????';//ok
TT_language_jp["cambialotodo.common.membersOnlyService3"]        = '???????????';//ok
TT_language_jp["cambialotodo.common.membersOnlyService4"]        = '?????????????';//ok
TT_language_jp["cambialotodo.common.membersOnlyService5"]        = '??????';//ok
TT_language_jp["cambialotodo.common.error"]                      = '???';
TT_language_jp["cambialotodo.common.successfully"]               = '??????';
TT_language_jp["cambialotodo.common.viewCartCheckOut"]           = '???????';//ok
TT_language_jp["cambialotodo.common.inStock"]                    = '???????';
TT_language_jp["cambialotodo.common.outStock"]                   = '????????';
TT_language_jp["cambialotodo.product.regularPrice"]              = '????';
TT_language_jp["cambialotodo.product.saleEndsIn"]                = '??????? ????';

TT_language_jp["cambialotodo.common.chinaWarehouse"]             = '????';
TT_language_jp["cambialotodo.common.ukWarehouse"]                = '??????';
TT_language_jp["cambialotodo.common.italyWarehouse"]             = '??????';
TT_language_jp["cambialotodo.common.germanyWarehouse"]           = '?????';
TT_language_jp["cambialotodo.common.usWarehouse"]                = '??????';
TT_language_jp["cambialotodo.common.franceWarehouse"]            = '??????';
TT_language_jp["cambialotodo.common.spainWarehouse"]             = '??????';
TT_language_jp["cambialotodo.common.australiaWarehouse"]         = '?????????';
TT_language_jp["cambialotodo.product.shippingFrom"]              = '????';
TT_language_jp["cambialotodo.product.warehouse"]                 = '??';
TT_language_jp["cambialotodo.shippingmethod.freeshipping"]       = '????';
TT_language_jp["cambialotodo.shippingmethod.noshipping"]         = '??????????????';
TT_language_jp["cambialotodo.shippingmethod.to"]                 = 'to';
TT_language_jp["cambialotodo.shippingmethod.via"]                = 'via';
TT_language_jp["cambialotodo.lottery.continueToDraw"]             = '????????';
TT_language_jp["cambialotodo.lottery.againDrawing"]               = '???????????';
TT_language_jp["cambialotodo.lottery.continueLater"]              = '?????';
TT_language_jp["cambialotodo.lottery.cancelTheDraw"]              = '??????????';
TT_language_jp["cambialotodo.product.pcsSold"]                     = '????';
TT_language_jp["cambialotodo.common.viewLess"]                   = '????????';
TT_language_jp["cambialotodo.common.preorder"]                   = '????';
TT_language_jp["cambialotodo.common.yes"]                        = '??';
TT_language_jp["cambialotodo.common.no"]                         = '???';
TT_language_jp["cambialotodo.common.youMayalsolike"]             = '?????????';
//Italiano id = 9
var TT_language_pl = new Array();
TT_language_pl["cambialotodo.message.shoppingCartIsEmpty"]       = 'Koszyk zakupowy jest pusty!';
TT_language_pl["cambialotodo.common.continueShopping"]           = 'Kontynuowac zakupy';
TT_language_pl["cambialotodo.message.cannotBeEmpty"]              = 'Can not byc pusty!';
TT_language_pl["cambialotodo.common.tip"]                        = 'Wskazówka';
TT_language_pl["cambialotodo.message.enterYourEmail"]          = 'Podaj swój adres e-mail.';
TT_language_pl["cambialotodo.message.wrongEmail"]                = 'You have wszedl w zlym formacie e-mail!';
TT_language_pl["cambialotodo.product.ok"]                        = 'Ok';//ok
TT_language_pl["cambialotodo.product.cancel"]                    = 'Anuluj';//ok
TT_language_pl["cambialotodo.product.name"]                      = 'Nazwa';//ok
TT_language_pl["cambialotodo.product.mobilePhone"]               = 'Telefon komórkowy';//ok
TT_language_pl["cambialotodo.product.emailAddress"]              = 'E-mail';//ok
TT_language_pl["cambialotodo.product.yourTargetPrice"]           = 'Twoja cena docelowa';//ok
TT_language_pl["cambialotodo.product.orderQuantity"]             = 'Ilosc zamówienia';//ok
TT_language_pl["cambialotodo.product.countryState"]              = 'Kraj / region';//ok
TT_language_pl["cambialotodo.product.companyName"]               = 'Nazwa firmy';//ok
TT_language_pl["cambialotodo.product.writeAnInquiry"]            = 'Wpisz zapytanie';//ok
TT_language_pl["cambialotodo.product.pleaseLetUsKnow"]           = 'Daj nam znac jak najwiecej o swoim pytania, tak, ze mozemy pomóc z konkretnych potrzeb. Jestesmy zawsze gotowi do pomocy, jesli mozliwe.';//ok
TT_language_pl["cambialotodo.product.item"]                      = 'Pozycja';//ok
TT_language_pl["cambialotodo.common.itemAddedToCart"]           = 'Element dodany do koszyka';
TT_language_pl["cambialotodo.common.totalItemInYourCart"]        = 'Calkowita pozycja w koszyku';
TT_language_pl["cambialotodo.common.viewCart"]                   = 'Zobacz Koszyk';
TT_language_pl["cambialotodo.product.addToCart"]                 = 'Dodaj do koszyka';//ok
TT_language_pl["cambialotodo.common.viewMore"]                   = 'Zobacz wiecej';
TT_language_pl["cambialotodo.message.enterYourPassword"]    = 'Wprowadz haslo.';
TT_language_pl["cambialotodo.message.usernameOrPassword"]         = 'Podales niewlasciwy login i haslo.';
TT_language_pl["cambialotodo.common.signIn"]                     = 'Zaloguj';
TT_language_pl["cambialotodo.common.signInWithcambialotodoAccount"]    = 'Zaloguj sie z kontem cambialotodo';//ok
TT_language_pl["cambialotodo.common.enterYourEmail"]             = 'Wprowadz swój email';//ok
TT_language_pl["cambialotodo.common.enterYourPassword"]          = 'Wprowadz haslo';//ok
TT_language_pl["cambialotodo.common.forgotPassword"]             = 'Zapomniales hasla?';//ok
TT_language_pl["cambialotodo.common.signInWithAnExistingAccount"]= 'Zaloguj sie z istniejacym kontem';//ok
TT_language_pl["cambialotodo.common.joinToday"]                  = 'Dolacz dzis!';//ok
TT_language_pl["cambialotodo.common.membersOnlyService"]         = 'Tylko uzytkownicy serwisowe';//ok
TT_language_pl["cambialotodo.common.membersOnlyService1"]        = '1.Reward Punkty';//ok
TT_language_pl["cambialotodo.common.membersOnlyService2"]        = '2.Exclusive Obslugi Klienta';//ok
TT_language_pl["cambialotodo.common.membersOnlyService3"]        = '3.Personalized Zalecenia';//ok
TT_language_pl["cambialotodo.common.membersOnlyService4"]        = '4.Permanent Koszyk';//ok
TT_language_pl["cambialotodo.common.membersOnlyService5"]        = '5.Order Historia';//ok
TT_language_pl["cambialotodo.common.error"]                      = 'Blad';
TT_language_pl["cambialotodo.common.successfully"]               = 'Z powodzeniem';
TT_language_pl["cambialotodo.common.viewCartCheckOut"]           = 'Vedi il Carrello';//??pl???
TT_language_pl["cambialotodo.common.inStock"]                    = 'w magazynie';
TT_language_pl["cambialotodo.common.outStock"]                   = 'Obecnie brak na stanie';
TT_language_pl["cambialotodo.product.regularPrice"]              = 'Normalna cena';
TT_language_pl["cambialotodo.product.saleEndsIn"]                = 'Sprzedaz konczy sie';

TT_language_pl["cambialotodo.common.chinaWarehouse"]             = 'Chiny Magazyn';
TT_language_pl["cambialotodo.common.ukWarehouse"]                = 'Magazyn w Wielkiej Brytanii';
TT_language_pl["cambialotodo.common.italyWarehouse"]             = 'Wlochy magazynowe';
TT_language_pl["cambialotodo.common.germanyWarehouse"]           = 'Niemcy Magazyn';
TT_language_pl["cambialotodo.common.usWarehouse"]                = 'US Magazyn';
TT_language_pl["cambialotodo.common.franceWarehouse"]            = 'Francja Magazyn';
TT_language_pl["cambialotodo.common.spainWarehouse"]             = 'Hiszpania Magazyn';
TT_language_pl["cambialotodo.common.australiaWarehouse"]         = 'Australia Magazyn';
TT_language_pl["cambialotodo.product.shippingFrom"]              = 'Statek z';
TT_language_pl["cambialotodo.product.warehouse"]                 = 'Magazyn';
TT_language_pl["cambialotodo.shippingmethod.freeshipping"]       = 'DARMOWA DOSTAWA';
TT_language_pl["cambialotodo.shippingmethod.noshipping"]         = 'Ta pozycja nie moze byc dostarczany';
TT_language_pl["cambialotodo.shippingmethod.to"]                 = 'do';
TT_language_pl["cambialotodo.shippingmethod.via"]                = 'przez';
TT_language_pl["cambialotodo.lottery.continueToDraw"]             = 'Kontynuuj rysowanie';
TT_language_pl["cambialotodo.lottery.againDrawing"]               = 'Ponownie rysunek';
TT_language_pl["cambialotodo.lottery.continueLater"]              = 'Kontynuuj pózniej';
TT_language_pl["cambialotodo.lottery.cancelTheDraw"]              = 'Anuluj losowanie';
TT_language_pl["cambialotodo.product.pcsSold"]                     = 'szt sprzedane';
TT_language_pl["cambialotodo.common.viewLess"]                   = 'Zobacz mniej';
TT_language_pl["cambialotodo.common.preorder"]                   = 'Przed Sprzedaz';
TT_language_pl["cambialotodo.common.yes"]                        = 'Tak';
TT_language_pl["cambialotodo.common.no"]                         = 'Nie';
TT_language_pl["cambialotodo.common.youMayalsolike"]             = 'Produkty, które moga Ci sie spodobac';
//???? id = 11
var TT_language_ar = new Array();
TT_language_ar["cambialotodo.message.shoppingCartIsEmpty"]       = '???? ?????? ?????!';
TT_language_ar["cambialotodo.common.continueShopping"]           = '?????? ??????';
TT_language_ar["cambialotodo.message.cannotBeEmpty"]             = '?? ???? ?? ???? ?????!';
TT_language_ar["cambialotodo.common.tip"]                        = '?????';
TT_language_ar["cambialotodo.message.enterYourEmail"]            = '???? ????? ????? ????? ?????????? .';
TT_language_ar["cambialotodo.message.wrongEmail"]                = '????? ???? ???????? ???? ??? ?????  ??? ????!';
TT_language_ar["cambialotodo.product.ok"]                        = '????';//ok
TT_language_ar["cambialotodo.product.cancel"]                    = '?????';//ok
TT_language_ar["cambialotodo.product.name"]                      = '???';//ok
TT_language_ar["cambialotodo.product.mobilePhone"]               = '?????? ???????';//ok
TT_language_ar["cambialotodo.product.emailAddress"]              = '????? ?????? ??????????';//ok
TT_language_ar["cambialotodo.product.yourTargetPrice"]           = '????? ????????';//ok
TT_language_ar["cambialotodo.product.orderQuantity"]             = '???? ???????';//ok
TT_language_ar["cambialotodo.product.countryState"]              = '????? / ???????';//ok
TT_language_ar["cambialotodo.product.companyName"]               = '??? ??????';//ok
TT_language_ar["cambialotodo.product.writeAnInquiry"]            = '????? ???????';//ok
TT_language_ar["cambialotodo.product.pleaseLetUsKnow"]           = '??????? ??? ?? ???? ?? ?????? ??? ????? ?? ??????? ?? ????????? ??????? . ??? ????? ????? ???????? ????? ??? ??? ???????.';//ok
TT_language_ar["cambialotodo.product.item"]                      = '????';//ok
TT_language_ar["cambialotodo.common.itemAddedToCart"]            = '???? ????? ??? ???? ??????';
TT_language_ar["cambialotodo.common.totalItemInYourCart"]        = '????? ????????? ?? ???? ??????';
TT_language_ar["cambialotodo.common.viewCart"]                   = '?????? ?????';
TT_language_ar["cambialotodo.product.addToCart"]                 = '????? ??? ?????';//ok
TT_language_ar["cambialotodo.common.viewMore"]                   = '?????? ??????';
TT_language_ar["cambialotodo.message.enterYourPassword"]         = '???? ????? ???? ??????.';
TT_language_ar["cambialotodo.message.usernameOrPassword"]        = '??? ????? ??? ??????  ?? ???? ???? ??? ?????.';
TT_language_ar["cambialotodo.common.signIn"]                     = '????? ??????';
TT_language_ar["cambialotodo.common.signInWithcambialotodoAccount"]    = '??? ?????? ???????? ???? ??????';//ok
TT_language_ar["cambialotodo.common.enterYourEmail"]             = '????? ????? ??????????';//ok
TT_language_ar["cambialotodo.common.enterYourPassword"]          = '????? ???? ??????';//ok
TT_language_ar["cambialotodo.common.forgotPassword"]             = '?? ???? ???? ???????';//ok
TT_language_ar["cambialotodo.common.signInWithAnExistingAccount"]= '????? ?????? ???????? ???? ?????';//ok
TT_language_ar["cambialotodo.common.joinToday"]                  = '???? ?????!';//ok
TT_language_ar["cambialotodo.common.membersOnlyService"]         = '????? ???????';//ok
TT_language_ar["cambialotodo.common.membersOnlyService1"]        = '????:?????? ??????';//ok
TT_language_ar["cambialotodo.common.membersOnlyService2"]        = '?????:???? ??????? ???????';//ok
TT_language_ar["cambialotodo.common.membersOnlyService3"]        = '?????:?????? ?????';//ok
TT_language_ar["cambialotodo.common.membersOnlyService4"]        = '?????:???? ?????? ???????';//ok
TT_language_ar["cambialotodo.common.membersOnlyService5"]        = '?????:????? ???????';//ok
TT_language_ar["cambialotodo.common.error"]                      = '???';
TT_language_ar["cambialotodo.common.successfully"]               = '?????';
TT_language_ar["cambialotodo.common.viewCartCheckOut"]           = 'Vedi il Carrello';//??pl???
TT_language_ar["cambialotodo.common.inStock"]                    = '????? ??? ?????';
TT_language_ar["cambialotodo.common.outStock"]                   = '????? ?? ???????';
TT_language_ar["cambialotodo.product.regularPrice"]              = '??? ????';
TT_language_ar["cambialotodo.product.saleEndsIn"]                = '????? ????? ?';

TT_language_ar["cambialotodo.common.chinaWarehouse"]             = '???????? ??????';
TT_language_ar["cambialotodo.common.ukWarehouse"]                = '???????? ?????????';
TT_language_ar["cambialotodo.common.italyWarehouse"]             = '???????? ?????????';
TT_language_ar["cambialotodo.common.germanyWarehouse"]           = '???????? ?????????';
TT_language_ar["cambialotodo.common.usWarehouse"]                = '???????? ????????';
TT_language_ar["cambialotodo.common.franceWarehouse"]            = '???????? ???????';
TT_language_ar["cambialotodo.common.spainWarehouse"]             = '???????? ?????????';
TT_language_ar["cambialotodo.common.australiaWarehouse"]         = '???????? ??????????';
TT_language_ar["cambialotodo.product.shippingFrom"]              = '????? ??';
TT_language_ar["cambialotodo.product.warehouse"]                 = '??????';
TT_language_ar["cambialotodo.shippingmethod.freeshipping"]       = '????? ?????';
TT_language_ar["cambialotodo.shippingmethod.noshipping"]         = '?? ???? ??? ??? ?????? ???';
TT_language_ar["cambialotodo.shippingmethod.to"]                 = '???';
TT_language_ar["cambialotodo.shippingmethod.via"]                = '??????';
TT_language_ar["cambialotodo.lottery.continueToDraw"]             = '????? ?? ???';
TT_language_ar["cambialotodo.lottery.againDrawing"]               = '???  ??? ????';
TT_language_ar["cambialotodo.lottery.continueLater"]              = '????? ?? ??? ????';
TT_language_ar["cambialotodo.lottery.cancelTheDraw"]              = '????? ???';
TT_language_ar["cambialotodo.product.pcsSold"]                     = '??? ????';
TT_language_ar["cambialotodo.common.viewLess"]                   = '?????? ?????';
TT_language_ar["cambialotodo.common.preorder"]                   = '??? ????';
TT_language_ar["cambialotodo.common.yes"]                        = '???';
TT_language_ar["cambialotodo.common.no"]                         = '??';
TT_language_ar["cambialotodo.common.youMayalsolike"]             = '???????? ?? ????';